### ISSUE TITLE
Missing xml files

### ISSUE THREAD

**Issue by Lallie101** [vogeltanz/ControlSystemDesignerForJSBSim#2]
Hi!

Thanks for the awesome project. 
It seems that some config/setup files are needed, for example:
I/O warning : failed to load external entity "templates/Control_Design/ziegler_nichols_rules.xml"

Best regards
Joe

**Comment by vogeltanz** [comment]
Yes, you're right. I'm sorry about that. I don't know why it was not included in the commit. I'll add the XML files soon.

**Comment by Lallie101** [comment]
Great, thanks!
